---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master
  namespace: mcm-devops-demo
  labels:
    volume: jenkins-master
    project: "mcm-devops-demo"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: NFS_SERVER_IP_ADDRESS
    path: /PATH/TO/NFS/VOLUME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-claim
  namespace: mcm-devops-demo
  labels:
    volume: jenkins-master
    project: "mcm-devops-demo"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: "jenkins-master"
  storageClassName: ""